server:
  port: 8080


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: llm-route
          uri: lb://LLM-SERVICE
          predicates:
            - Path=/llm/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/