server:
  port: 8080


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: llm-route
          uri: http://localhost:8081
          predicates:
            - Path=/llm/**